Repository aurora-is-near/aurora-engine, pull requests merged in 2021-04, with the labels that each got.

#17 JSON parser
  src/json.rs
  src/lib.rs
  src/sdk.rs
Labels: enhancement

#20 fix meta parsing test
  src/meta_parsing.rs
  src/parameters.rs
  src/types.rs
  tests/test_meta_parsing.rs
Labels: enhancement

#25 Fix: Makefile
  Makefile
Labels: enhancement

#26 Add twice weekly run of nightly clippy
  .github/workflows/scheduled_lints.yml
Labels: enhancement

#27 Fix: Use clippy on contract code too
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  Makefile
  src/engine.rs
  src/lib.rs
Labels: enhancement

#29 References in fungible token
  src/connector.rs
  src/fungible_token.rs
Labels: enhancement

#37 feat: add `transfer` method to engine
  src/engine.rs
  src/lib.rs
Labels: enhancement

#24 EVM tokens deposit & withdraw
  Cargo.toml
  Makefile
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/lib.rs
  src/parameters.rs
  src/prover.rs
  src/sdk.rs
  src/types.rs
  tests/test_connector.rs
  tests/test_upgrade.rs
Labels: enhancement

#18 Link to NEAR docs in README.
  README.md
Labels: documentation

#38 chore: change deprecated `u64::max_value` to `u64::MAX`
  src/engine.rs
Labels: enhancement

#40 feat: return formatted custom messages
  src/lib.rs
Labels: enhancement

#30 Implement necessary contract method `begin_chain` for `evm-bully`.
  src/lib.rs
  src/parameters.rs
  src/types.rs
Labels: enhancement

#39 feat: faucet
  Cargo.toml
  src/engine.rs
  src/lib.rs
Labels: enhancement

#21 feat: add precompiles
  Cargo.lock
  Cargo.toml
  src/meta_parsing.rs
  src/precompiles.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/transaction.rs
Labels: enhancement

#42 Feat: Check and increment nonce
  src/engine.rs
  src/lib.rs
  src/types.rs
Labels: enhancement

#44 Fix Precompiles: RIPEMD160, modexp
  src/precompiles/hash.rs
  src/precompiles/modexp.rs
Labels: bug

#47 fix: gas_limit
  src/engine.rs
Labels: bug
