Repository aurora-is-near/aurora-engine, pull requests merged in 2021-07, with the labels that each got.

#168 Remove Prover - deprecated EIP-712 implementation
  src/connector.rs
  src/lib.rs
  src/prover.rs
  src/types.rs
Labels: enhancement

#171 ERC-20: allow admin to change metadata
  Makefile
  etc/eth-contracts/contracts/EvmErc20.sol
  etc/eth-contracts/hardhat.config.js
  etc/eth-contracts/package.json
  etc/eth-contracts/test/EvmErc20.js
  etc/eth-contracts/yarn.lock
Labels: P0, enhancement

#172 Release 1.4.3
  .github/workflows/scheduled_lints.yml
  CHANGES.md
  Makefile
  VERSION
  etc/eth-contracts/contracts/EvmErc20.sol
  etc/eth-contracts/hardhat.config.js
  etc/eth-contracts/package.json
  etc/eth-contracts/test/EvmErc20.js
  etc/eth-contracts/yarn.lock
  src/admin_controlled.rs
  src/connector.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/modexp.rs
  src/prover.rs
  src/test_utils/erc20.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/standard_precompiles.rs
  src/tests/erc20_connector.rs
  src/tests/eth_connector.rs
  src/tests/mod.rs
  src/tests/sanity.rs
  src/transaction.rs
  src/types.rs
Labels: release

#141 JSON: bugs fixes, add unit tests.
  src/json.rs
  src/lib.rs
Labels: enhancement, tests

#190 Feat(engine): Use new math API host functions
  Cargo.lock
  Cargo.toml
  src/precompiles/hash.rs
  src/precompiles/secp256k1.rs
  src/sdk.rs
  src/test_utils/mod.rs
  src/tests/eth_connector.rs
  src/tests/state_migration.rs
  src/transaction/legacy.rs
Labels: enhancement

#204 Add options to bench profile
  Cargo.toml
Labels: bug

#206 Sanity test for access list handling
  src/test_utils/mod.rs
  src/tests/access_lists.rs
  src/tests/mod.rs
Labels: enhancement

#179 ERC-20: forbid using invalid NEP141 AccountID for mapping
  src/engine.rs
  src/lib.rs
  src/parameters.rs
Labels: enhancement

#207 Release 1.5.0
  .github/workflows/builds.yml
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  .github/workflows/tests.yml
  .gitignore
  CHANGES.md
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  VERSION
  etc/eth-contracts/hardhat.config.js
  etc/eth-contracts/package.json
  etc/eth-contracts/tasks/storage.js
  etc/eth-contracts/yarn.lock
  etc/state-migration-test/Cargo.lock
  src/connector.rs
  src/engine.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/sdk.rs
  src/test_utils/mod.rs
  src/tests/access_lists.rs
  src/tests/erc20.rs
  src/tests/eth_connector.rs
  src/tests/mod.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/tests/state_migration.rs
  src/transaction/access_list.rs
  src/transaction/legacy.rs
  src/transaction/mod.rs
Labels: release
