Repository aurora-is-near/aurora-engine, pull requests merged in 2021-11, with the labels that each got.

#317 Release 2.0.0
  .github/workflows/builds.yml
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  .github/workflows/tests.yml
  CHANGES.md
  Cargo.lock
  VERSION
  engine-precompiles/src/modexp.rs
  engine-precompiles/src/secp256k1.rs
  engine-tests/Cargo.toml
  engine-tests/src/benches/mod.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  engine/src/parameters.rs
  etc/state-migration-test/Cargo.lock
Labels: C-release

#320 Release 2.0.1.
  CHANGES.md
  Cargo.lock
  VERSION
  engine/Cargo.toml
  engine/src/lib.rs
Labels: P-high, C-release

#326 Modify message verification inside ft_transfer_call for external receiver_id
  .gitignore
  Cargo.toml
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/rust.rs
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/state_migration.rs
  engine/src/connector.rs
  engine/src/fungible_token.rs
  engine/src/parameters.rs
  etc/ft-receiver/Cargo.lock
  etc/ft-receiver/Cargo.toml
  etc/ft-receiver/src/lib.rs
Labels: C-enhancement

#329 Fix ripemd160 word cost
  engine-precompiles/src/hash.rs
Labels: C-bug, P-high, A-precompiles

#331 Release 2.1.0
  .gitignore
  CHANGES.md
  Cargo.lock
  Cargo.toml
  README.md
  VERSION
  engine-precompiles/src/hash.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/rust.rs
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/state_migration.rs
  engine/Cargo.toml
  engine/src/connector.rs
  engine/src/fungible_token.rs
  engine/src/parameters.rs
  etc/ft-receiver/Cargo.lock
  etc/ft-receiver/Cargo.toml
  etc/ft-receiver/src/lib.rs
  etc/state-migration-test/Cargo.lock
Labels: C-release

#333 Test asserting we do not change the engine state binary format
  engine-tests/src/tests/sanity.rs
Labels: A-testing

#318 Introduce new Account ID data structure
  engine-precompiles/src/native.rs
  engine-precompiles/src/prelude.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/contract_call.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/state_migration.rs
  engine-types/src/account_id.rs
  engine-types/src/lib.rs
  engine-types/src/parameters.rs
  engine-types/src/types.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/parameters.rs
  engine/src/prelude.rs
Labels: C-enhancement

#337 Fix 0x prefix on address, if there
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/sanity.rs
  engine-types/src/types.rs
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/lib.rs
Labels: C-bug, P-critical, C-incident, A-connector

#244 Add initial EIP-1559 support
  Cargo.lock
  engine-precompiles/src/lib.rs
  engine-tests/src/benches/nft_pagination.rs
  engine-tests/src/test_utils/erc20.rs
  engine-tests/src/test_utils/exit_precompile.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/one_inch/liquidity_protocol.rs
  engine-tests/src/test_utils/self_destruct.rs
  engine-tests/src/test_utils/solidity.rs
  engine-tests/src/test_utils/standard_precompiles.rs
  engine-tests/src/test_utils/uniswap.rs
  engine-tests/src/tests/access_lists.rs
  engine-tests/src/tests/eip1559.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/mod.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
  engine-types/src/types.rs
  engine/src/engine.rs
  engine/src/lib.rs
  engine/src/transaction/eip_1559.rs
  engine/src/transaction/eip_2930.rs
  engine/src/transaction/legacy.rs
  engine/src/transaction/mod.rs
  etc/state-migration-test/Cargo.lock
Labels: C-enhancement, P-high, C-dependencies, A-benchmark, A-testing

#311 Refund user when ExitToNear promise fails
  Makefile
  engine-precompiles/Cargo.toml
  engine-precompiles/src/native.rs
  engine-tests/Cargo.toml
  engine-tests/src/test_utils/exit_precompile.rs
  engine-tests/src/tests/contract_call.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/res/fungible_token.wasm
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/state_migration.rs
  engine-types/src/parameters.rs
  engine/Cargo.toml
  engine/src/engine.rs
  engine/src/lib.rs
  etc/eth-contracts/.soliumignore
  etc/eth-contracts/contracts/EvmErc20V2.sol
  etc/eth-contracts/contracts/test/TesterV2.sol
  etc/eth-contracts/main.js
  etc/eth-contracts/package.json
Labels: C-enhancement, P-high, A-connector, A-testing, A-fungible-token

#314 Parameterize Engine Access to Storage
  engine-precompiles/src/native.rs
  engine-sdk/src/error.rs
  engine-sdk/src/io.rs
  engine-sdk/src/lib.rs
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/types.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/sanity.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  engine/src/map.rs
  etc/state-migration-test/src/lib.rs
Labels: C-enhancement, A-connector, A-storage, A-fungible-token

#341 Test verifying the EVM log returns the correct address
  engine-tests/src/test_utils/solidity.rs
  engine-tests/src/tests/res/caller.sol
  engine-tests/src/tests/sanity.rs
Labels: A-testing

#340 Release 2.2.0
  CHANGES.md
  README.md
  VERSION
  engine-precompiles/src/native.rs
  engine-precompiles/src/prelude.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/contract_call.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/state_migration.rs
  engine-types/src/account_id.rs
  engine-types/src/lib.rs
  engine-types/src/parameters.rs
  engine-types/src/types.rs
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  engine/src/parameters.rs
  engine/src/prelude.rs
Labels: C-release

#346 Remove sdk::current_account_id usage from engine-precompiles
  engine-precompiles/src/blake2.rs
  engine-precompiles/src/bn128.rs
  engine-precompiles/src/hash.rs
  engine-precompiles/src/identity.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine-precompiles/src/native.rs
  engine-precompiles/src/secp256k1.rs
  engine-tests/src/tests/erc20.rs
  engine/src/engine.rs
Labels: A-precompiles, A-standalone

#347 Remove some sdk usage from core logic
  engine/src/admin_controlled.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
Labels: A-connector, A-standalone

#349 Factor out blockchain environment variable access as a trait
  engine-sdk/src/env.rs
  engine-sdk/src/error.rs
  engine-sdk/src/lib.rs
  engine-sdk/src/near_runtime.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  etc/state-migration-test/src/lib.rs
Labels: A-standalone

#353 Factor out NEAR promise host functions into a trait (#353)
  engine-sdk/src/lib.rs
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/promise.rs
  engine-types/src/parameters.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
Labels: A-standalone

#355 Refactor(eth-connector): Use Result return values instead of panicking
  engine-tests/src/tests/one_inch.rs
  engine-types/src/types.rs
  engine/src/admin_controlled.rs
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/engine.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  engine/src/parameters.rs
Labels: A-connector, A-standalone

#356 Gate all NEAR host functions behind the contract feature
  Cargo.lock
  engine-sdk/Cargo.toml
  engine-sdk/src/lib.rs
  engine-sdk/src/promise.rs
  engine-sdk/src/types.rs
  engine-tests/Cargo.toml
  engine/Cargo.toml
  engine/src/engine.rs
  etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.toml
Labels: A-standalone

#344 Chore: Newtypes for gas
  engine-precompiles/src/blake2.rs
  engine-precompiles/src/bn128.rs
  engine-precompiles/src/hash.rs
  engine-precompiles/src/identity.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine-precompiles/src/native.rs
  engine-precompiles/src/secp256k1.rs
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/prelude.rs
  engine-types/src/lib.rs
  engine-types/src/types.rs
  engine/src/connector.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
Labels: P-low, C-housekeeping, A-precompiles

#345 Feat(standalone): Standalone
  Cargo.lock
  Cargo.toml
  Makefile
  engine-precompiles/src/lib.rs
  engine-sdk/Cargo.toml
  engine-sdk/src/env.rs
  engine-sdk/src/promise.rs
  engine-standalone/Cargo.toml
  engine-standalone/LICENSE
  engine-standalone/src/ffi.rs
  engine-standalone/src/main.rs
  engine-standalone/src/tests/mocks/mod.rs
  engine-standalone/src/tests/mocks/promise.rs
  engine-standalone/src/tests/mocks/storage.rs
  engine-standalone/src/tests/mod.rs
  engine-standalone/src/tests/sanity.rs
  engine-standalone/src/trace.rs
  engine-types/src/parameters.rs
  engine-types/src/types.rs
Labels: C-enhancement, P-critical, A-standalone

#366 Refactor(engine): Move submit logic into engine module
  engine/src/engine.rs
  engine/src/lib.rs
  engine/src/transaction/mod.rs
Labels: A-standalone

#357 Fix: Meta parsing imports
  engine-tests/Cargo.toml
  engine-tests/src/prelude.rs
  engine-tests/src/tests/meta_parsing.rs
Labels: C-bug, P-low, A-testing
