Repository aurora-is-near/aurora-engine, pull requests merged in 2021-08, with the labels that each got.

#208 Timestamp should be in milliseconds for Ethereum compatibility
  src/sdk.rs
Labels: bug

#211 Update etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.lock
Labels: bug

#219 Feat(Engine): Include cost of access list in intrinsic gas
  src/transaction/mod.rs
Labels: enhancement

#215 Feat(engine): Relayer payment
  src/engine.rs
  src/lib.rs
  src/tests/erc20.rs
  src/tests/sanity.rs
  src/transaction/mod.rs
  src/types.rs
Labels: enhancement

#214 Fix(CI): Scheduled lint is supposed to run nightly clippy
  .github/workflows/scheduled_lints.yml
Labels: bug, continuous Integration

#218 Return actual status of a transaction
  src/engine.rs
  src/lib.rs
  src/parameters.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/tests/erc20.rs
  src/tests/erc20_connector.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/tests/state_migration.rs
  src/types.rs
Labels: bug, P0

#183 Added parser for Integer types
  Cargo.lock
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  src/json.rs
Labels: enhancement

#223 Fix(engine): do not panic when user has insufficient balance to cover gas
  src/lib.rs
  src/tests/sanity.rs
Labels: bug

#202 NEP-141 compliance correctness
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  src/connector.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/storage.rs
  src/test_utils/mod.rs
  src/tests/eth_connector.rs
  src/tests/sanity.rs
  src/tests/state_migration.rs
Labels: enhancement

#233 Fix(blockhash): Move block height to the end of hashing data
  src/engine.rs
  src/tests/res/blockhash.sol
  src/tests/sanity.rs
Labels: enhancement

#235 Release 1.6.0
  .github/workflows/builds.yml
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  .github/workflows/tests.yml
  .gitignore
  CHANGES.md
  Cargo.lock
  Cargo.toml
  Makefile
  VERSION
  etc/eth-contracts/yarn.lock
  etc/state-migration-test/Cargo.lock
  rust-toolchain
  src/connector.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/hash.rs
  src/precompiles/mod.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/sdk.rs
  src/storage.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/solidity.rs
  src/test_utils/standard_precompiles.rs
  src/tests/erc20.rs
  src/tests/erc20_connector.rs
  src/tests/eth_connector.rs
  src/tests/res/blockhash.sol
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/tests/state_migration.rs
  src/transaction/mod.rs
  src/types.rs
Labels: release

#240 Drop lazy static in test-utils
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  src/test_utils/mod.rs
Labels: bug, continuous Integration

#241 Fix return format of `ft_balance_of`
  src/connector.rs
  src/tests/eth_connector.rs
Labels: bug, P0

#246 Return view of transaction result as borsh
  CHANGES.md
  src/lib.rs
Labels: bug, BREAKING

#249 Release 1.6.1
  .github/workflows/tests.yml
  CHANGES.md
  Cargo.lock
  Cargo.toml
  VERSION
  src/connector.rs
  src/lib.rs
  src/test_utils/mod.rs
  src/tests/eth_connector.rs
  src/tests/sanity.rs
Labels: release

#253 Feat(benches): Profile NFT paginated view call
  src/benches/mod.rs
  src/benches/nft_pagination.rs
  src/test_utils/solidity.rs
Labels: enhancement
