Repository aurora-is-near/aurora-engine, pull requests merged in 2021-05, with the labels that each got.

#49 feat: Better errors
  src/engine.rs
  src/lib.rs
  src/meta_parsing.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/prelude.rs
  src/types.rs
Labels: enhancement

#48 fix: logs
  src/engine.rs
  src/lib.rs
  src/parameters.rs
  src/types.rs
Labels: bug, enhancement

#41 Aurora Engine Benchmarks
  Cargo.lock
  Cargo.toml
  benches/eth_deploy_code.rs
  benches/eth_erc20.rs
  benches/eth_standard_precompiles.rs
  benches/eth_transfer.rs
  benches/main.rs
  benches/res/StandardPrecompiles.sol
  benches/solidity.rs
  src/engine.rs
  src/lib.rs
  src/sdk.rs
Labels: enhancement

#50 Improved EVM token master branch update
  Cargo.lock
  Cargo.toml
  README.md
  benches/eth_deploy_code.rs
  benches/eth_erc20.rs
  benches/eth_standard_precompiles.rs
  benches/eth_transfer.rs
  benches/main.rs
  benches/res/StandardPrecompiles.sol
  benches/solidity.rs
  src/connector.rs
  src/engine.rs
  src/fungible_token.rs
  src/lib.rs
  src/meta_parsing.rs
  src/parameters.rs
  src/precompiles.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/transaction.rs
  src/types.rs
Labels: enhancement

#36 Improved ETH connector logic
  Cargo.lock
  Cargo.toml
  README.md
  benches/eth_deploy_code.rs
  benches/eth_erc20.rs
  benches/eth_standard_precompiles.rs
  benches/eth_transfer.rs
  benches/main.rs
  benches/res/StandardPrecompiles.sol
  benches/solidity.rs
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/meta_parsing.rs
  src/parameters.rs
  src/precompiles.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/transaction.rs
  src/types.rs
  tests/test_connector.rs
Labels: enhancement

#60 Sanity tests
  Cargo.toml
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/benches/mod.rs
  src/benches/res/StandardPrecompiles.sol
  src/lib.rs
  src/test_utils/mod.rs
  src/test_utils/solidity.rs
  src/tests/mod.rs
  src/tests/sanity.rs
Labels: enhancement

#61 Fix transaction decoding
  src/transaction.rs
Labels: bug

#62 Add common code between #51 and #59
  README.md
  src/engine.rs
  src/lib.rs
  src/map.rs
  src/sdk.rs
  src/storage.rs
  tests/test_meta_parsing.rs
Labels: enhancement

#63 More simple Engine tests
  Cargo.lock
  Cargo.toml
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/benches/mod.rs
  src/test_utils/erc20.rs
  src/test_utils/mod.rs
  src/test_utils/solidity.rs
  src/test_utils/standard_precompiles.rs
  src/tests/erc20.rs
  src/tests/mod.rs
  src/tests/standard_precompiles.rs
Labels: enhancement

#71 Fix sanity tests in connector
  Cargo.toml
  src/connector.rs
  src/engine.rs
  src/fungible_token.rs
  src/lib.rs
  src/parameters.rs
  src/prelude.rs
  src/storage.rs
  src/test_utils/mod.rs
Labels: enhancement

#74 Eugene audit 2021 05 11
  src/engine.rs
  src/lib.rs
  src/meta_parsing.rs
  src/sdk.rs
  src/storage.rs
Labels: bug, documentation, enhancement

#77 Add storage version prefix.
  src/storage.rs
Labels: enhancement

#78 Fix versioned storage scheme byte lengths.
  src/storage.rs
Labels: bug

#79 Implement versioned states.
  src/engine.rs
  src/lib.rs
Labels: bug, enhancement

#80 Update evm-core to 0.26.1
  Cargo.lock
  Cargo.toml
Labels: bug

#81 Explicitly use `evm-core` 0.26.1.
  Cargo.lock
  Cargo.toml
Labels: bug

#83 Remove unused VersionPrefixU8
  src/storage.rs
Labels: enhancement

#73 Base precompile code between connectors
  src/precompiles/mod.rs
  src/precompiles/native.rs
  src/prelude.rs
  src/sdk.rs
  src/types.rs
Labels: enhancement

#85 Fix(tests): Track storage usage in AuroraRunner
  src/test_utils/mod.rs
Labels: bug

#92 Use cache action to save cargo artifacts between runs
  .github/workflows/tests.yml
Labels: Continuous Integration, enhancement

#86 Address comments from Audit
  src/engine.rs
  src/lib.rs
  src/meta_parsing.rs
  src/sdk.rs
Labels: enhancement

#95 Reduce size of cargo cache in CI
  .github/workflows/tests.yml
Labels: continuous Integration, enhancement

#96 Newtype for amounts in Wei
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/engine.rs
  src/lib.rs
  src/meta_parsing.rs
  src/prelude.rs
  src/test_utils/mod.rs
  src/tests/erc20.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/transaction.rs
  src/types.rs
  tests/test_meta_parsing.rs
Labels: enhancement

#100 Fix(evm-bully): Fixes after recent refactoring
  src/lib.rs
Labels: bug, enhancement

#99 Refactor Engine::get_state
  src/engine.rs
  src/lib.rs
Labels: enhancement

#101 Ensure that Cargo.lock in the repo is valid
  .github/workflows/tests.yml
Labels: bug, continuous Integration

#102 Remove unneeded nightly feature
  src/lib.rs
  src/sdk.rs
Labels: enhancement

#104 Eth connector statistic
  src/connector.rs
  src/fungible_token.rs
  src/lib.rs
  src/storage.rs
  tests/test_connector.rs
Labels: enhancement

#97 Eugene's Eth connector review
  Cargo.lock
  Cargo.toml
  src/connector.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/native.rs
  src/prelude.rs
  src/storage.rs
  tests/test_connector.rs
Labels: enhancement

#106 Eth-connector extended proof tests
  tests/test_connector.rs
Labels: tests

#88 EthConnector: make AdminControlled and pausable
  src/admin_controlled.rs
  src/connector.rs
  src/lib.rs
  src/parameters.rs
  src/storage.rs
  tests/test_connector.rs
Labels: enhancement

#107 Fix(precompiles): Match on full address when dispatching on precompiles
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
Labels: bug, enhancement

#103 Support state migration on upgrade
  .gitignore
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.toml
  etc/state-migration-test/src/lib.rs
  src/lib.rs
  src/sdk.rs
  tests/test_state_migration.rs
  tests/test_upgrade.rs
Labels: enhancement

#109 Eth-connector: merge `develop` branch
  .github/workflows/tests.yml
  .gitignore
  Cargo.toml
  README.md
  etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.toml
  etc/state-migration-test/src/lib.rs
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/engine.rs
  src/fungible_token.rs
  src/lib.rs
  src/meta_parsing.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/test_utils/mod.rs
  src/tests/erc20.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/transaction.rs
  src/types.rs
  tests/test_meta_parsing.rs
  tests/test_state_migration.rs
Labels: P0, enhancement

#112 Eth-connector: restrict contract initialization to owner.
  src/lib.rs
  tests/test_connector.rs
Labels: P0, enhancement

#111 Eth-connector: add compilation feature for exit precompiles.
  Cargo.toml
  src/precompiles/mod.rs
  src/precompiles/native.rs
Labels: P0, enhancement

#113 Eth-connector: add the way to set contract data. Minor refactoring.
  src/connector.rs
  src/lib.rs
  src/parameters.rs
Labels: P0, enhancement

#59 ETH connector
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  Makefile
  doc/eth-connector.md
  etc/state-migration-test/Cargo.lock
  src/admin_controlled.rs
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/mod.rs
  src/precompiles/native.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/storage.rs
  src/test_utils/mod.rs
  src/types.rs
  tests/test_connector.rs
  tests/test_upgrade.rs
Labels: enhancement
