Repository aurora-is-near/aurora-engine, pull requests merged in 2021-09, with the labels that each got.

#259 Chore: Upgrade nearcore dependencies to latest commit
  Cargo.lock
  Cargo.toml
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/solidity.rs
  src/tests/erc20.rs
  src/tests/erc20_connector.rs
  src/tests/eth_connector.rs
  src/tests/meta_parsing.rs
  src/tests/sanity.rs
  src/tests/state_migration.rs
Labels: enhancement, dependencies

#261 1inch deploy benchmark
  src/tests/mod.rs
  src/tests/one_inch.rs
Labels: tests

#264 Release 1.6.2
  .github/CODEOWNERS
  CHANGES.md
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  VERSION
  etc/eth-contracts/package.json
  etc/eth-contracts/yarn.lock
  etc/state-migration-test/Cargo.lock
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/benches/mod.rs
  src/benches/nft_pagination.rs
  src/connector.rs
  src/engine.rs
  src/lib.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/state.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/solidity.rs
  src/tests/contract_call.rs
  src/tests/erc20.rs
  src/tests/erc20_connector.rs
  src/tests/eth_connector.rs
  src/tests/meta_parsing.rs
  src/tests/mod.rs
  src/tests/one_inch.rs
  src/tests/sanity.rs
  src/tests/state_migration.rs
Labels: C-release

#265 Test counting the number of functions in our wasm contract
  Cargo.lock
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  src/tests/sanity.rs
Labels: A-testing

#267 Fix issue with admin only contract call
  src/connector.rs
  src/engine.rs
  src/lib.rs
  src/test_utils/mod.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/sanity.rs
Labels: C-bug, P-critical

#271 Test for overriding state
  src/tests/res/poster.sol
  src/tests/sanity.rs
Labels: A-testing, A-storage

#268 Release 1.6.3.
  CHANGES.md
  Cargo.lock
  Cargo.toml
  README.md
  VERSION
  etc/state-migration-test/Cargo.lock
  src/connector.rs
  src/engine.rs
  src/lib.rs
  src/test_utils/mod.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/res/poster.sol
  src/tests/sanity.rs
Labels: P-critical, C-release

#274 Test for 1inch liquidity protocol
  src/test_utils/erc20.rs
  src/test_utils/mod.rs
  src/test_utils/one_inch/liquidity_protocol.rs
  src/test_utils/one_inch/mod.rs
  src/test_utils/solidity.rs
  src/tests/one_inch.rs
Labels: A-benchmark, A-testing

#277 Fix(deploy benchmark): Realistic deploy transaction
  src/benches/eth_deploy_code.rs
  src/test_utils/mod.rs
  src/tests/sanity.rs
Labels: A-benchmark

#279 Fix json formatting in JsonValue serialization
  engine/src/json.rs
Labels: C-bug, P-high, A-fungible-token

#280 Update primitive-types dependency to 0.10
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-tests/Cargo.toml
  engine-types/Cargo.toml
  engine/Cargo.toml
  etc/state-migration-test/Cargo.lock
Labels: P-high, C-dependencies

#287 Fix block.timestamp
  engine-sdk/src/lib.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/res/timestamp.sol
  engine-tests/src/tests/sanity.rs
Labels: C-bug, P-high, A-evm-compatibility
