Repository aurora-is-near/aurora-engine, pull requests merged in 2021-06, with the labels that each got.

#115 Remove dependency on Lunarity
  Cargo.lock
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  src/meta_parsing.rs
Labels: enhancement

#117 Fix: nightly clippy checks
  src/types.rs
Labels: enhancement

#121 Add evm-bully=yes build to CI
  .github/workflows/tests.yml
Labels: continuous Integration, enhancement

#87 Implement generational storage
  .github/workflows/tests.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  doc/eth-connector.md
  etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.toml
  etc/state-migration-test/src/lib.rs
  src/admin_controlled.rs
  src/benches/eth_deploy_code.rs
  src/benches/eth_erc20.rs
  src/benches/eth_standard_precompiles.rs
  src/benches/eth_transfer.rs
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/meta_parsing.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/storage.rs
  src/test_utils/mod.rs
  src/tests/erc20.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/transaction.rs
  src/types.rs
  tests/test_connector.rs
  tests/test_meta_parsing.rs
  tests/test_state_migration.rs
  tests/test_upgrade.rs
Labels: enhancement

#130 Fix(bully): compilation
  src/lib.rs
Labels: P1, bug

#123 Fix(engine): handle transaction gas limit properly
  src/engine.rs
  src/lib.rs
  src/test_utils/erc20.rs
  src/test_utils/mod.rs
  src/test_utils/standard_precompiles.rs
  src/tests/erc20.rs
  src/tests/sanity.rs
  src/transaction.rs
Labels: P0, bug, enhancement

#116 Update to `evm_core` 0.27.1
  Cargo.lock
  Cargo.toml
  etc/state-migration-test/Cargo.lock
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
Labels: P0, enhancement

#120 EthConnector: add view function to check whether the proof is used.
  src/connector.rs
  src/lib.rs
  src/parameters.rs
  tests/test_connector.rs
Labels: P0, enhancement, tests

#118 Simplify sdk::read_u64 return type
  src/fungible_token.rs
  src/lib.rs
  src/sdk.rs
Labels: P1, enhancement

#135 Fix needless borrows
  src/connector.rs
  src/engine.rs
  src/lib.rs
  src/meta_parsing.rs
  src/precompiles/modexp.rs
Labels: enhancement

#131 Add JSON custom error types. Refactoring.
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/types.rs
Labels: P0, enhancement

#133 EthConnector: don't burn NEP-141 on deposit.
  src/connector.rs
  tests/test_connector.rs
Labels: P0, enhancement

#125 Eth-connector: fixed u128 json parsing & tests
  src/json.rs
  tests/test_connector.rs
Labels: P0, enhancement

#51 Introduce precompiles to manage ERC20 connector
  .github/workflows/lints.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  etc/eth-contracts/.soliumignore
  etc/eth-contracts/.soliumrc.json
  etc/eth-contracts/contracts/AdminControlled.sol
  etc/eth-contracts/contracts/EvmErc20.sol
  etc/eth-contracts/contracts/IExit.sol
  etc/eth-contracts/contracts/test/StateTest.sol
  etc/eth-contracts/contracts/test/Tester.sol
  etc/eth-contracts/main.js
  etc/eth-contracts/package.json
  etc/state-migration-test/Cargo.lock
  etc/state-migration-test/Cargo.toml
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/log_entry.rs
  src/map.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/prover.rs
  src/sdk.rs
  src/state.rs
  src/storage.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/solidity.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/mod.rs
  src/tests/sanity.rs
  src/tests/standard_precompiles.rs
  src/types.rs
Labels: enhancement

#136 Eth-connector: change `total_supply` behaviour. Refactoring.
  doc/eth-connector.md
  src/connector.rs
  src/fungible_token.rs
  src/lib.rs
  src/test_utils/mod.rs
  tests/test_connector.rs
Labels: P0, enhancement

#145 Fix debug pipeline
  Makefile
Labels: bug, continuous Integration

#146 Add `meta-call` feature flag
  Cargo.toml
  Makefile
  src/lib.rs
  tests/test_meta_parsing.rs
Labels: P2, enhancement

#138 Add EIP-2565 support
  src/precompiles/modexp.rs
Labels: P1, enhancement

#147 Add `mainnet`, `testnet`, `betanet`; remove `exit-precompiles` compilation features
  Cargo.toml
  Makefile
  README.md
  src/precompiles/mod.rs
  src/precompiles/native.rs
Labels: enhancement

#149 Fix clippy::unnecessary_unwrap
  src/connector.rs
Labels: enhancement

#148 Exit precompiles: forbid static calling context. ERC-20: don't use static calls.
  etc/eth-contracts/contracts/EvmErc20.sol
  src/precompiles/native.rs
Labels: P0, bug

#150 Fix warnings
  src/deposit_event.rs
  src/fungible_token.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/test_utils/exit_precompile.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/sanity.rs
  src/types.rs
  tests/test_meta_parsing.rs
Labels: enhancement

#151 Fix(ExitToNear): register the receiver account if it does not exist
  src/fungible_token.rs
Labels: P0, bug

#152 Release 1.4.0
  CHANGES.md
  Cargo.toml
  Makefile
  README.md
  etc/eth-contracts/contracts/EvmErc20.sol
  etc/eth-contracts/yarn.lock
  src/connector.rs
  src/deposit_event.rs
  src/fungible_token.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/test_utils/exit_precompile.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/sanity.rs
  src/types.rs
  tests/test_meta_parsing.rs
Labels: release

#153 Fix debug CI pipeline
  Makefile
Labels: continuous Integration

#156 Remove duplicate import of the context contract
  etc/eth-contracts/contracts/EvmErc20.sol
Labels: enhancement

#157 Properly document endianess.
  src/types.rs
Labels: documentation

#158 Fix NEP-141 Compliance
  src/connector.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/tests/erc20_connector.rs
Labels: P0, bug

#159 Release 1.4.1
  .github/workflows/tests.yml
  CHANGES.md
  Cargo.lock
  Cargo.toml
  Makefile
  etc/eth-contracts/contracts/EvmErc20.sol
  etc/state-migration-test/Cargo.toml
  src/connector.rs
  src/deposit_event.rs
  src/engine.rs
  src/fungible_token.rs
  src/json.rs
  src/lib.rs
  src/parameters.rs
  src/precompiles/blake2.rs
  src/precompiles/bn128.rs
  src/precompiles/hash.rs
  src/precompiles/identity.rs
  src/precompiles/mod.rs
  src/precompiles/modexp.rs
  src/precompiles/native.rs
  src/precompiles/secp256k1.rs
  src/prelude.rs
  src/sdk.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/tests/contract_call.rs
  src/tests/erc20_connector.rs
  src/tests/meta_parsing.rs
  src/tests/mod.rs
  src/tests/state_migration.rs
  src/types.rs
  tests/test_upgrade.rs
Labels: release

#163 Release 1.4.2
  CHANGES.md
  VERSION
Labels: release

#162 Tests: always compile with `mainnet` feature enabled.
  Makefile
Labels: tests

#164 Move eth-connector tests under `src`, remove duplicate code
  src/admin_controlled.rs
  src/connector.rs
  src/parameters.rs
  src/tests/eth_connector.rs
  src/tests/mod.rs
  src/types.rs
Labels: enhancement

#165 EIP-2718: Typed Transaction Envelope support
  src/lib.rs
  src/test_utils/erc20.rs
  src/test_utils/exit_precompile.rs
  src/test_utils/mod.rs
  src/test_utils/self_destruct.rs
  src/test_utils/standard_precompiles.rs
  src/tests/erc20_connector.rs
  src/tests/sanity.rs
  src/transaction.rs
Labels: P1, enhancement
