Repository aurora-is-near/aurora-engine, pull requests merged in 2022-01, with the labels that each got.

#406 Feat(benchmarks): update gas bounds after wasm cost reduction
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
Labels: C-enhancement, A-benchmark

#408 Feat(tests): Mock touching trie nodes
  engine-tests/src/test_utils/mocked_external.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
Labels: A-benchmark

#410 Fix: Only allow owner to call deploy_upgrade
  engine/src/lib.rs
Labels: A-security

#412 Additional log data for Submit
  engine/src/lib.rs
Labels: C-enhancement

#424 Fix(engine): Return revert error message during contract deploy
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/lib.rs
  engine-standalone-storage/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-tests/Cargo.toml
  engine-tests/src/tests/res/reverter.sol
  engine-tests/src/tests/sanity.rs
  engine/Cargo.toml
  engine/src/engine.rs
  etc/state-migration-test/Cargo.lock
Labels: C-bug, A-evm-compatibility, A-engine

#418 Move engine transactions module to engine-transactions crate
  Cargo.lock
  Cargo.toml
  engine-precompiles/Cargo.toml
  engine-sdk/Cargo.toml
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/relayer_db/mod.rs
  engine-standalone-storage/src/relayer_db/types.rs
  engine-standalone-storage/src/sync/types.rs
  engine-standalone-tracing/Cargo.toml
  engine-tests/Cargo.toml
  engine-tests/src/benches/nft_pagination.rs
  engine-tests/src/prelude.rs
  engine-tests/src/test_utils/erc20.rs
  engine-tests/src/test_utils/exit_precompile.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/one_inch/liquidity_protocol.rs
  engine-tests/src/test_utils/random.rs
  engine-tests/src/test_utils/self_destruct.rs
  engine-tests/src/test_utils/solidity.rs
  engine-tests/src/test_utils/standalone/mocks/block.rs
  engine-tests/src/test_utils/standalone/mod.rs
  engine-tests/src/test_utils/standard_precompiles.rs
  engine-tests/src/test_utils/uniswap.rs
  engine-tests/src/test_utils/weth.rs
  engine-tests/src/tests/access_lists.rs
  engine-tests/src/tests/eip1559.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/standalone/sync.rs
  engine-tests/src/tests/standalone/tracing.rs
  engine-transactions/Cargo.toml
  engine-transactions/src/eip_1559.rs
  engine-transactions/src/eip_2930.rs
  engine-transactions/src/legacy.rs
  engine-transactions/src/lib.rs
  engine-types/Cargo.toml
  engine/Cargo.toml
  engine/src/engine.rs
  engine/src/lib.rs
  engine/src/prelude.rs
  etc/state-migration-test/Cargo.lock
Labels: C-enhancement

#429 Benchmark contract performing only pure arithmetic and memory operations
  engine-tests/src/test_utils/solidity.rs
  engine-tests/src/tests/res/bench.sol
  engine-tests/src/tests/sanity.rs
Labels: A-benchmark
