Repository aurora-is-near/aurora-engine, pull requests merged in 2022-11, with the labels that each got.

#628 Feat(tests): Test for trying to obtain TransactionStatus::CallTooDeep from the Engine
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/promise_result.rs
  engine-standalone-storage/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-test-doubles/Cargo.toml
  engine-tests/Cargo.toml
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/res/CallTooDeep.sol
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
  engine-transactions/Cargo.toml
  engine/Cargo.toml
Labels: C-bug, A-testing, A-evm-compatibility

#622 Fix(xcc): Ensure the xcc router attaches enough gas to the execute function
  engine-precompiles/src/xcc.rs
  engine-tests/src/tests/xcc.rs
  engine-types/src/parameters.rs
Labels: C-bug, A-precompiles

#637 fix: bn256 regression
  engine-precompiles/src/alt_bn256.rs
Labels: C-bug, P-high, A-precompiles

#638 Chore: Update to SputnikVM version v0.37.1-aurora
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-standalone-storage/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-test-doubles/Cargo.toml
  engine-tests/Cargo.toml
  engine-transactions/Cargo.toml
  engine-types/Cargo.toml
  engine/Cargo.toml
  etc/xcc-router/Cargo.lock
Labels: C-dependencies, A-security

#640 ci: fix docker build
  Makefile.toml
Labels: P-high, A-ci

#641 Feat(tests): Test showing SputnikVM does not experience integer overflow in gas calculation
  engine-tests/src/tests/sanity.rs
Labels: A-testing

#644 chore: merge 2.8.0 `master` into `develop`
  CHANGES.md
  Cargo.lock
  Makefile.toml
  README.md
  VERSION
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine/Cargo.toml
Labels: C-housekeeping, A-engine

#645 Chore: Update to SputnikVM `v0.37.2-aurora`
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-standalone-storage/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-test-doubles/Cargo.toml
  engine-tests/Cargo.toml
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/uniswap.rs
  engine-transactions/Cargo.toml
  engine/Cargo.toml
Labels: C-dependencies
