Repository aurora-is-near/aurora-engine, pull requests merged in 2022-10, with the labels that each got.

#614 Test(engine): Increase unit test coverage
  Cargo.lock
  Cargo.toml
  engine-sdk/src/env.rs
  engine-test-doubles/Cargo.toml
  engine-test-doubles/src/io.rs
  engine-test-doubles/src/lib.rs
  engine-test-doubles/src/promise.rs
  engine-test-doubles/src/tracing.rs
  engine-tests/Cargo.toml
  engine-tests/src/test_utils/standalone/mocks/mod.rs
  engine-tests/src/tests/standalone/sanity.rs
  engine/Cargo.toml
  engine/src/accounting.rs
  engine/src/admin_controlled.rs
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/log_entry.rs
  engine/src/map.rs
  engine/src/proof.rs
Labels: C-housekeeping, A-testing

#618 Test(engine): Increase unit test coverage
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/lib.rs
  engine-standalone-storage/src/sync/mod.rs
  engine-test-doubles/src/io.rs
  engine-test-doubles/src/promise.rs
  engine/Cargo.toml
  engine/src/engine.rs
  engine/src/json.rs
  engine/src/lib.rs
  engine/src/pausables.rs
Labels: C-housekeeping, A-testing

#617 Refactor: Mark functions that create promises on NEAR as unsafe
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/promise.rs
  engine-standalone-storage/src/promise.rs
  engine-test-doubles/src/promise.rs
  engine/src/engine.rs
  engine/src/lib.rs
  engine/src/xcc.rs
Labels: A-security

#616 Fix(xcc): Only update the router contract version in storage if the deploy is successful
  engine/src/lib.rs
Labels: C-enhancement

#615 Chore(standalone): Upgrade rocksdb to v0.19.
  .github/workflows/lints.yml
  Cargo.lock
  Makefile.toml
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/engine_state.rs
  engine-standalone-storage/src/lib.rs
  engine-test-doubles/src/promise.rs
  engine-tests/Cargo.toml
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/uniswap.rs
  engine-types/src/account_id.rs
  engine/Cargo.toml
  engine/src/deposit_event.rs
  engine/src/engine.rs
  engine/src/json.rs
  rust-toolchain
Labels: C-dependencies
