Repository aurora-is-near/aurora-engine, pull requests merged in 2022-07, with the labels that each got.

#546 Merge: 2.6.1 into `develop` from `master`
  AUTHORS
  CHANGES.md
  Cargo.lock
  README.md
  TODO.md
  VERSION
  engine-precompiles/src/native.rs
  engine-sdk/Cargo.toml
  engine-sdk/src/near_runtime.rs
  engine-standalone-tracing/Cargo.toml
  engine-standalone-tracing/src/sputnik.rs
  engine-standalone-tracing/src/types/mod.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/ghsa_3p69_m8gg_fwmf.rs
  engine-tests/src/tests/mod.rs
  engine-tests/src/tests/res/echo.sol
  engine-tests/src/tests/res/exploit.sol
  engine/Cargo.toml
  engine/src/engine.rs
  engine/src/lib.rs
  etc/self-contained-5bEgfRQ/Cargo.lock
  etc/state-migration-test/Cargo.lock
Labels: C-housekeeping

#535 Constant error messages
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/engine.rs
  engine/src/errors.rs
  engine/src/fungible_token.rs
  engine/src/json.rs
  engine/src/lib.rs
  engine/src/parameters.rs
Labels: A-binary-size

#378 Chore: Cargo make
  .env/custom_example.env
  .env/local.env
  .env/mainnet.env
  .env/testnet.env
  .github/workflows/builds.yml
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  .github/workflows/tests.yml
  .gitignore
  Makefile
  Makefile.toml
  README.md
  engine-tests/Cargo.toml
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/uniswap.rs
  engine/Cargo.toml
  etc/eth-contracts/contracts/test/Random.sol
  etc/eth-contracts/package.json
  verify_evm_erc20.sh
Labels: P-low, A-ci, C-housekeeping, A-build, A-testing

#548 Chore: PR template
  .github/pull_request_template.md
  bin/aurora-local.wasm
  bin/aurora-mainnet-test.wasm
  bin/aurora-mainnet.wasm
  bin/aurora-mainnet2.wasm
  bin/aurora-testnet-test.wasm
Labels: C-housekeeping
