Repository aurora-is-near/aurora-engine, pull requests merged in 2022-08, with the labels that each got.

#565 Chore(engine): Update to latest version of SputnikVM
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/account_ids.rs
  engine-precompiles/src/blake2.rs
  engine-precompiles/src/bn128.rs
  engine-precompiles/src/hash.rs
  engine-precompiles/src/identity.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine-precompiles/src/native.rs
  engine-precompiles/src/prepaid_gas.rs
  engine-precompiles/src/random.rs
  engine-precompiles/src/secp256k1.rs
  engine-standalone-storage/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-standalone-tracing/src/sputnik.rs
  engine-standalone-tracing/src/types/call_tracer.rs
  engine-tests/Cargo.toml
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/uniswap.rs
  engine-transactions/Cargo.toml
  engine-types/Cargo.toml
  engine/Cargo.toml
  etc/state-migration-test/Cargo.lock
Labels: C-dependencies

#566 Chore(CI): Update checkout to version 3
  .github/workflows/builds.yml
  .github/workflows/lints.yml
  .github/workflows/scheduled_lints.yml
  .github/workflows/tests.yml
Labels: C-housekeeping

#561 Chore: Disallow as_conversions
  .env/local.env
  .env/mainnet.env
  .env/testnet.env
  Cargo.lock
  engine-precompiles/src/blake2.rs
  engine-precompiles/src/bn128.rs
  engine-precompiles/src/hash.rs
  engine-precompiles/src/identity.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine-precompiles/src/utils.rs
  engine-sdk/src/near_runtime.rs
  engine-standalone-storage/src/sync/types.rs
  engine-standalone-tracing/Cargo.toml
  engine-tests/src/test_utils/erc20.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/sanity.rs
  engine-transactions/src/backwards_compatibility.rs
  engine-transactions/src/eip_1559.rs
  engine-transactions/src/eip_2930.rs
  engine-transactions/src/legacy.rs
  engine-transactions/src/lib.rs
  engine-types/src/lib.rs
  engine-types/src/storage.rs
  engine-types/src/types/gas.rs
  engine-types/src/types/mod.rs
  engine/src/connector.rs
  engine/src/engine.rs
  engine/src/errors.rs
  engine/src/fungible_token.rs
  engine/src/json.rs
  engine/src/lib.rs
Labels: C-housekeeping, A-security

#573 Fix(engine-transactions): Prevent panic on empty input
  engine-transactions/src/lib.rs
Labels: C-bug

#575 Feat(engine): Get promise results precompile
  engine-precompiles/src/lib.rs
  engine-precompiles/src/prepaid_gas.rs
  engine-precompiles/src/promise_result.rs
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/promise.rs
  engine-standalone-storage/src/promise.rs
  engine-standalone-storage/src/relayer_db/mod.rs
  engine-standalone-storage/src/sync/mod.rs
  engine-standalone-storage/src/sync/types.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/standalone/mocks/promise.rs
  engine-tests/src/test_utils/standalone/mod.rs
  engine-tests/src/tests/mod.rs
  engine-tests/src/tests/promise_results_precompile.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/standalone/storage.rs
  engine-tests/src/tests/standalone/sync.rs
  engine-tests/src/tests/standalone/tracing.rs
  engine-types/src/lib.rs
  engine-types/src/types/gas.rs
  engine-types/src/types/mod.rs
  engine/src/engine.rs
Labels: C-enhancement, A-precompiles

#581 Fix(engine): Return correct value for get_bridge_prover function
  engine/src/connector.rs
  engine/src/lib.rs
Labels: C-bug

#571 Chore: Cleanup dead dependencies
  .github/workflows/lints.yml
  Cargo.lock
  Makefile.toml
  engine-precompiles/Cargo.toml
  engine-precompiles/src/utils.rs
  engine-sdk/Cargo.toml
  engine-standalone-tracing/Cargo.toml
  engine-tests/Cargo.toml
  engine-transactions/Cargo.toml
  engine-types/Cargo.toml
  engine/Cargo.toml
  engine/src/lib.rs
  engine/src/meta_parsing.rs
  engine/src/parameters.rs
  engine/src/proof.rs
Labels: C-housekeeping

#570 Chore(Precompiles): Ripemd160 lib deprecated
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/hash.rs
Labels: C-housekeeping

#540 Feat(precompiles): Use near host functions for alt_bn128
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/alt_bn256.rs
  engine-precompiles/src/lib.rs
  engine-sdk/src/lib.rs
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/prelude.rs
  engine-tests/Cargo.toml
  engine-tests/src/test_utils/standard_precompiles.rs
  engine-tests/src/tests/standard_precompiles.rs
  engine-tests/src/tests/uniswap.rs
  etc/state-migration-test/Cargo.lock
Labels: C-dependencies, A-precompiles

#584 Chore(eth-contracts): Update openzeppelin to 4.7.3
  etc/eth-contracts/package.json
  etc/eth-contracts/yarn.lock
Labels: C-dependencies

#585 Fix: Make binaries on push
  .github/workflows/builds.yml
Labels: C-bug, A-ci

#586 Feat(standalone): Conversion from standalone's TransactionKind to NormalizedEthTransaction
  Cargo.lock
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/sync/types.rs
  engine-types/src/types/address.rs
  engine/src/engine.rs
Labels: C-enhancement, A-standalone
