Repository aurora-is-near/aurora-engine, pull requests merged in 2022-04, with the labels that each got.

#479 Feat(Engine): Add custom precompile for NEAR prepaid_gas
  engine-precompiles/src/account_ids.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/native.rs
  engine-precompiles/src/prepaid_gas.rs
  engine-precompiles/src/random.rs
  engine-tests/src/tests/mod.rs
  engine-tests/src/tests/prepaid_gas_precompile.rs
Labels: A-precompiles

#485 Test: Reproduce 8ru7VEAEbyfZdbC1W2PYQv2cY3W92rbTToDEN4yTp8aZ gas failure
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/res/aurora_state_8ru7VEA.json
  engine-tests/src/tests/res/input_8ru7VEA.hex
Labels: A-benchmark, A-testing

#482 Feat(standalone): Function to get latest/earliest block
  engine-standalone-storage/src/lib.rs
  engine-tests/src/tests/standalone/storage.rs
Labels: C-enhancement, A-standalone

#488 Engine optimization: cache all reads from NEAR state
  engine-sdk/src/caching.rs
  engine-sdk/src/dup_cache.rs
  engine-sdk/src/lib.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/uniswap.rs
  engine/src/engine.rs
Labels: C-enhancement

#484 Fix near-blake2 dependency
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/blake2.rs
  engine/Cargo.toml
  etc/state-migration-test/Cargo.lock
Labels: C-enhancement

#496 Feat(standalone): thread-safety and serde
  engine-standalone-storage/src/lib.rs
  engine-standalone-storage/src/relayer_db/mod.rs
  engine-standalone-storage/src/sync/mod.rs
  engine-tests/src/test_utils/standalone/mod.rs
  engine-tests/src/tests/standalone/storage.rs
  engine-tests/src/tests/standalone/sync.rs
  engine-transactions/src/lib.rs
  engine/Cargo.toml
  engine/src/engine.rs
  engine/src/parameters.rs
Labels: A-standalone

#497 Refactor repro tests to have less boilerplate
  engine-tests/src/tests/repro.rs
Labels: A-benchmark, A-testing
