Repository aurora-is-near/aurora-engine, pull requests merged in 2023-05, with the labels that each got.

#751 chore: update near dependencies and bump rust version
  Cargo.lock
  engine-precompiles/src/xcc.rs
  engine-tests/Cargo.toml
  engine-tests/src/benches/eth_deploy_code.rs
  engine-tests/src/benches/eth_erc20.rs
  engine-tests/src/benches/eth_standard_precompiles.rs
  engine-tests/src/benches/eth_transfer.rs
  engine-tests/src/benches/nft_pagination.rs
  engine-tests/src/benches/uniswap.rs
  engine-tests/src/test_utils/exit_precompile.rs
  engine-tests/src/test_utils/mocked_external.rs
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/test_utils/rust.rs
  engine-tests/src/test_utils/self_destruct.rs
  engine-tests/src/test_utils/solidity.rs
  engine-tests/src/test_utils/standalone/mod.rs
  engine-tests/src/tests/contract_call.rs
  engine-tests/src/tests/eip1559.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/eth_connector.rs
  engine-tests/src/tests/ghsa_3p69_m8gg_fwmf.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/pausable_precompiles.rs
  engine-tests/src/tests/promise_results_precompile.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/uniswap.rs
  engine-tests/src/tests/xcc.rs
  engine/Cargo.toml
  rust-toolchain
Labels: A-testing

#744 chore: add build flow for xcc-router smart contract
  .env/mainnet.env
  .env/testnet.env
  .github/workflows/builds.yml
  Makefile.toml
  scripts/docker-xcc-router-entrypoint.sh
Labels: A-build

#757 Fix(engine): More efficient modexp implementation
  Cargo.lock
  Cargo.toml
  Makefile.toml
  engine-modexp/Cargo.toml
  engine-modexp/README.md
  engine-modexp/src/arith.rs
  engine-modexp/src/lib.rs
  engine-modexp/src/maybe_std.rs
  engine-modexp/src/mpnat.rs
  engine-precompiles/Cargo.toml
  engine-precompiles/src/modexp.rs
  engine-tests/src/tests/modexp.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/standard_precompiles.rs
  etc/tests/modexp-bench/Cargo.toml
  etc/tests/modexp-bench/res/evm_contract_1.hex
  etc/tests/modexp-bench/res/evm_contract_2.hex
  etc/tests/modexp-bench/src/lib.rs
Labels: C-enhancement, A-benchmark, A-precompiles

#760 Fix(modexp): remove leading zeros when factoring modulus
  engine-modexp/src/mpnat.rs
  engine-tests/src/tests/modexp.rs
Labels: C-bug, P-high, A-precompiles

#767 Fix: use single crate for borsh version, allow to choose borsh v0.9 for all crates
  Cargo.lock
  engine-precompiles/Cargo.toml
  engine-precompiles/src/prelude.rs
  engine-precompiles/src/promise_result.rs
  engine-precompiles/src/xcc.rs
  engine-sdk/Cargo.toml
  engine-sdk/src/io.rs
  engine-sdk/src/prelude.rs
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/diff.rs
  engine-standalone-storage/src/sync/types.rs
  engine-tests/src/test_utils/erc20.rs
  engine-types/src/lib.rs
  engine/Cargo.toml
  engine/src/connector.rs
  engine/src/deposit_event.rs
  engine/src/fungible_token.rs
  engine/src/lib.rs
  engine/src/parameters.rs
  engine/src/pausables.rs
  engine/src/prelude.rs
  engine/src/proof.rs
  engine/src/state.rs
  engine/src/xcc.rs
Labels: C-dependencies
