Repository aurora-is-near/aurora-engine, pull requests merged in 2023-07, with the labels that each got.

#788 chore: precompile librocksdb for speed up tests
  .github/workflows/tests.yml
  scripts/ci/build_rocksdb.sh
Labels: A-ci

#787 chore: fix scheduled CI task
  .github/workflows/scheduled_lints.yml
Labels: A-ci

#783 feat(ci): create release builds after pushing tag
  .github/workflows/builds.yml
Labels: A-ci

#794 feat: remove owner requirement on deploying a staged upgrade
  .github/workflows/tests.yml
  engine/src/lib.rs
Labels: C-enhancement, P-high, A-engine

#796 Release 2.9.3
  .github/workflows/tests.yml
  CHANGES.md
  Cargo.lock
  VERSION
  engine/Cargo.toml
  engine/src/lib.rs
  etc/eth-contracts/yarn.lock
Labels: C-release

#799 chore: 2.10.0 release notes
  CHANGES.md
  Makefile.toml
  VERSION
  engine/Cargo.toml
Labels: C-docs
