Repository aurora-is-near/aurora-engine, pull requests merged in 2023-08, with the labels that each got.

#811 Fix(modexp): re-enable Aurora implementation
  engine-modexp/Cargo.toml
  engine-modexp/src/lib.rs
  engine-tests/src/tests/modexp.rs
  engine-tests/src/tests/repro.rs
Labels: C-enhancement, A-precompiles, rust

#810 Feat(standalone): logic for parsing TransactionKind from raw Near data
  Cargo.lock
  Cargo.toml
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/error.rs
  engine-standalone-storage/src/sync/mod.rs
  engine-standalone-storage/src/sync/types.rs
  engine-tests/src/tests/contract_call.rs
  engine-tests/src/tests/erc20_connector.rs
  engine-tests/src/tests/modexp.rs
  engine-tests/src/tests/pausable_precompiles.rs
  engine-tests/src/tests/pause_contract.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/xcc.rs
  engine-tests/src/utils/mod.rs
  engine-tests/src/utils/standalone/mocks/mod.rs
  engine-tests/src/utils/standalone/mod.rs
Labels: C-enhancement, A-testing, rust

#815 fix: missing exit errors
  engine/src/engine.rs
  engine/src/errors.rs
Labels: P-high, C-incident, A-engine

#817 Fix(tracing): Do not panic on empty call stack
  .github/workflows/lints.yml
  engine-standalone-tracing/src/types/call_tracer.rs
  engine-tests/src/tests/res/contract_data_too_large.hex
  engine-tests/src/tests/standalone/call_tracer.rs
Labels: C-bug, A-standalone

#816 Feat: core hashchain logic
  Cargo.lock
  Cargo.toml
  engine-hashchain/Cargo.toml
  engine-hashchain/src/bloom.rs
  engine-hashchain/src/error.rs
  engine-hashchain/src/hashchain.rs
  engine-hashchain/src/lib.rs
  engine-hashchain/src/merkle.rs
  engine-hashchain/src/tests.rs
Labels: C-enhancement

#826 Chore: Update to SputnikVM version 0.38.3
  Cargo.lock
  Cargo.toml
  Makefile.toml
  engine-precompiles/src/promise_result.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/sanity.rs
Labels: C-bug, C-dependencies, A-evm-compatibility, A-engine

#825 Fix(standalone): Do not eagerly commit transactions to the DB
  engine-standalone-storage/src/sync/mod.rs
  engine-tests/src/tests/standalone/sync.rs
Labels: C-enhancement, A-standalone

#827 Chore: factor logic out of all top-level contract methods
  engine/src/contract_methods/admin.rs
  engine/src/contract_methods/connector.rs
  engine/src/contract_methods/evm_transactions.rs
  engine/src/contract_methods/mod.rs
  engine/src/contract_methods/xcc.rs
  engine/src/lib.rs
Labels: C-housekeeping

#828 Release 3.0.0
  CHANGES.md
  Cargo.lock
  Cargo.toml
  Makefile.toml
  VERSION
  engine-hashchain/Cargo.toml
  engine-hashchain/src/bloom.rs
  engine-hashchain/src/error.rs
  engine-hashchain/src/hashchain.rs
  engine-hashchain/src/lib.rs
  engine-hashchain/src/merkle.rs
  engine-hashchain/src/tests.rs
  engine-precompiles/src/promise_result.rs
  engine-standalone-storage/src/sync/mod.rs
  engine-tests/src/tests/one_inch.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/sanity.rs
  engine-tests/src/tests/standalone/sync.rs
  engine/Cargo.toml
Labels: C-release

#832 Feat: update clippy requirements to `nightly-2023-08-24` without changing toolchain
  engine-hashchain/src/bloom.rs
  engine-precompiles/src/alt_bn256.rs
  engine-precompiles/src/lib.rs
  engine-precompiles/src/modexp.rs
  engine-standalone-storage/src/json_snapshot/mod.rs
  engine-standalone-tracing/src/sputnik.rs
  engine-tests/src/tests/erc20.rs
  engine-tests/src/tests/repro.rs
  engine-tests/src/tests/standalone/json_snapshot.rs
  engine-tests/src/tests/transaction.rs
  engine-tests/src/tests/uniswap.rs
  engine-tests/src/tests/xcc.rs
  engine-tests/src/utils/mod.rs
  engine-tests/src/utils/standalone/mod.rs
  engine-types/src/types/mod.rs
  engine/src/engine.rs
  engine/src/lib.rs
Labels: C-dependencies
