Repository aurora-is-near/aurora-engine, pull requests merged in 2023-02, with the labels that each got.

#673 chore: update some rust dependencies
  Cargo.lock
  engine-sdk/Cargo.toml
  engine-sdk/src/base64.rs
  engine-sdk/src/lib.rs
  engine-standalone-storage/Cargo.toml
  engine-standalone-storage/src/json_snapshot/mod.rs
  engine-standalone-storage/src/lib.rs
  engine-tests/Cargo.toml
  engine-tests/src/test_utils/mod.rs
  engine-tests/src/tests/standalone/json_snapshot.rs
  engine/Cargo.toml
  engine/src/fungible_token.rs
Labels: C-dependencies, rust

#671 fix: incremented nonce on out of fund failure
  engine-tests/src/tests/sanity.rs
  engine/src/engine.rs
Labels: C-bug, P-high, C-incident, A-engine

#693 Fix: check promise results before executing XCC callbacks
  engine-sdk/src/near_runtime.rs
  engine-sdk/src/promise.rs
  engine/src/lib.rs
  etc/xcc-router/src/lib.rs
Labels: C-bug

#694 Feat: enable XCC on mainnet
  engine/src/engine.rs
Labels: A-precompiles

#704 Fix: re-enable deriving serde traits
  engine-tests/Cargo.toml
  engine-tests/src/tests/mod.rs
  engine-tests/src/tests/serde.rs
  engine-types/src/parameters/engine.rs
  engine/src/engine.rs
Labels: C-bug
